### ISSUE TITLE
Unable to RUn API Samples

### ISSUE THREAD

**Issue by tbrooke** [groupdocs/groupdocs-ruby#65]
I am using Ruby 2.2.0

I am trying to run the Ruby API Samples and I get the following errors:
```
/Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext/module/deprecation.rb:21:in `deprecate': uninitialized constant ActiveSupport::Deprecation (NameError)
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext/class.rb:2:in `require'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext/class.rb:2:in `<top (required)>'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:2:in `require'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
''
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:1:in `each'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:1:in `<top (required)>'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/groupdocs-1.5.7/lib/groupdocs/api.rb:1:in `require'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/groupdocs-1.5.7/lib/groupdocs/api.rb:1:in `<top (required)>'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/groupdocs-1.5.7/lib/groupdocs.rb:3:in `require'
	from /Users/tmb/brookesons/groupdocs-ruby/examples/api-samples/vendor/bundle/gems/groupdocs-1.5.7/lib/groupdocs.rb:3:in `<top (required)>'
	from web.rb:2:in `require'
	from web.rb:2:in `<main>'
```

**Comment by 3skif9** [comment]
Hello Tom,

We are sorry to hear that you have such issue. We investigated the issue and updated our GroupDocs Ruby Samples so they support Ruby v2.2 now. Please try to run their now, follow these comands:
- bundle update
- bundle exec ruby web.rb
 

<p>Best regards
Evgen Efimov<br>
<a href="http://groupdocs.com">http://groupdocs.com</a><br>Your Document Collaboration APIs<br>Follow us on <a href="http://www.linkedin.com/company/groupdocs">LinkedIn</a>, <a href="https://twitter.com/groupdocs">Twitter</a>, <a href="https://www.facebook.com/GroupDocsApp">Facebook</a> and <a href="https://plus.google.com/+GroupDocs">Google+</a>
